# Terminal Colors
export CLICOLOR=1
export TERM="xterm-256color"

# Bash History Options
export HISTSIZE=32768
export HISTFILESIZE=${HISTSIZE} # bash will remember N commands
export HISTCONTROL=ignoreboth   # ingore duplicates and spaces
export HISTIGNORE='&:ll:la:ls:[bf]g:exit:pwd:clear:history'
export HISTTIMEFORMAT='%b %d %H:%M:%S: '
shopt -s histappend
set cmdhist
export EDITOR=atom
export PAGER=less
export MANPAGER="less -X"

export DOTDIR=$HOME/.dotfiles

alias ls='ls --color=auto'
alias l='ls -F'
alias la='ls -alhF'
alias ll='ls -alhF'
alias h='history |grep'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias df='df -h'
alias mkdir='mkdir -p -v'
alias more='less'
export LESS="-X -M -E -R"
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

export PATH=$HOME/bin:/usr/local/bin:${PATH}

alias emacs='/usr/local/bin/emacs' # just in case $PATH gets confused
eval "$(pyenv init -)"

